package cn.itsqh.ydma.entity;

import java.util.Date;

public class CollectNote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.user_id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.note_id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    private Integer noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_note.collect_time
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.id
     *
     * @return the value of collect_note.id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.id
     *
     * @param id the value for collect_note.id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.user_id
     *
     * @return the value of collect_note.user_id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.user_id
     *
     * @param userId the value for collect_note.user_id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.note_id
     *
     * @return the value of collect_note.note_id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public Integer getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.note_id
     *
     * @param noteId the value for collect_note.note_id
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_note.collect_time
     *
     * @return the value of collect_note.collect_time
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_note.collect_time
     *
     * @param collectTime the value for collect_note.collect_time
     *
     * @mbg.generated Mon Jul 08 21:55:04 CST 2019
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}